### PR TITLE
Update de-DE/-AT/-CH dictionaries to version 20180701

### PR DESCRIPTION
**Pull request by Eagle3386**
The author, Björn Jacke, updated all three dictionaries back in 2018, but AFAICT, only published them bundled as Firefox/Thunderbird extensions - though, encoded as ISO-8859-1 instead of UTF-8.
This PR updates them all to that very version, including all copyrights & docs, but except their encodings which were converted to UTF-8.

### CODE REVIEW

**Comment by wooorm** [comment]
@Eagle3386 Appreciate the work, but all these dictionaries are generated by code from sources. Next time that happens, that’ll overwrite your changes. See https://github.com/wooorm/dictionaries#contributing for more info

**Comment by Eagle3386** [comment]
@wooorm Since sources might be outdated or even down for good, the script should allow for such situations - AFAIK, Björn didn't release the newer dictionaries for a reason.
Besides, `crawl.sh` seems to be a Shell script, yet I'm on Win 10, hence no BASH, etc. available.

**Comment by wooorm** [comment]
> Besides, crawl.sh seems to be a Shell script, yet I'm on Win 10, hence no BASH, etc. available.

There are ways to run Bash on Windows

> Since sources might be outdated or even down for good, the script should allow for such situations - AFAIK, Björn didn't release the newer dictionaries for a reason.

Being down is one thing. Yes, there are safeguards for that.
However, it’s not feasible to manually handle dictionaries from sources. So, it has to be automated or I can’t accept the burden of maintaining it.

**Comment by wooorm** [comment]
I'd appreciate an automated solution that does this but I can't accept something that I'd have to maintain manually, sorry.

**Pull request closed without merging**
