### PR TITLE
Add Belarusian

### PR DESCRIPTION
**Pull request by noomorph**
Source: https://github.com/mikalai-udodau/spell-be

:pray: It is very convenient to work with `dictionary-**` convention on npm, but, as I see, there is a gap for Belarusian language which currently is a blocker in one of my recent projects.

### CODE REVIEW

**Comment by wooorm** [comment]
Hi Yaroslav. Please see: https://github.com/wooorm/dictionaries#adding-a-new-dictionary

Notably, this does not add information on how to crawl the dictionary in the script.
I could do that for you, separately.

However, 3 years of not updating, only 3 stars, that’s all a rather bad sign. It looks like the library isn’t used or maintained

**Comment by noomorph** [comment]
@wooorm hopefully I understood your request and fixed my PR correctly. The generation/crawling part seemed tricky for me to sit with it for a long time, so I used another repo with ready-to-use *.dic and *.aff files for Debian (https://github.com/375gnu/hunspell-be).

**Comment by wooorm** [comment]
I looked at this a bit, but I am rather unfomfortable with a) a dictionary that isn’t updated, b) an asset repo that might never get updates.

Can you ask if the assets can be maintained in that repo too? Or, as GH released if not in the master/main branch? That would also be a sign that it is still maintained. I can do the rest.

**Comment by noomorph** [comment]
@ssvb  As the author of this PR, I don't realy care about this situation. I published the package already as `dictionary-be` on npm, so you can use it as expected

**Pull request closed without merging**
