### PR TITLE
added hindi language

### PR DESCRIPTION
**Pull request by shantanuo**

### CODE REVIEW

**Comment by wooorm** [comment]
Thanks for working on this! I see you’ve contributed to https://github.com/Shreeshrii/hindi-hunspell. Could you confirm whether these are good quality dictionaries?

Could you also provide info on the other dictionaries maintained there? `sa_IN` and `mr_IN` seem too small to work properly, and what about `sa-Latn` and `sa-Deva`?

**Comment by wooorm** [comment]
@shantanuo Ping!

**Comment by shantanuo** [comment]
Yes. Hindi is good quality dictionary. I will check others and let you know.

**Comment by wooorm** [comment]
Did you find out about the other dictionaries? Thanks

**Comment by shantanuo** [comment]
Can you please merge this PR?
I will create a new issue for other languages. Once I see the hindi results, I will know if other languages are suitable for the commit.

**Comment by wooorm** [comment]
> Once I see the hindi results, I will know if other languages are suitable for the commit.

This seems to contradict your earlier statements that “Hindi is good quality dictionary.”? 🤔

**Comment by akarshanbiswas** [comment]
@wooorm sa-Latn and sa-Deva seems very good. They are Sanskrit dictionaries. Is it possible to add them?

**Comment by wooorm** [comment]
Cool! Could you clarify for me what `dict-sa_IN` and `dict-hi_IN` then are?

**Comment by akarshanbiswas** [comment]
@wooorm  
dict-sa_IN is same as sa-Deva but it is much smaller in size.
dict-hi_IN is the dictionary for Hindi language.

**Pull request closed without merging**
