### PR TITLE
Add Persian

### PR DESCRIPTION
**Pull request by wooorm**
Closes GH-10.

Co-authored-by: Ahmad Javadi Nejad <ahmadjavadi17@gmail.com>

### CODE REVIEW

**Comment by wooorm** [comment]
@AhmadJavadiNejad What do you think of this instead of GH-10?
The reason for a new PR is that all dictionaries in this project come from another place. They are added by `script/crawl.sh`, and code does the rest if you run `npm test`.

In your PR, you added the files by hand, which lead to inconsistencies.

I also opted to use `fa` as the name of the package, as we use the optimal BCP-47 for other dictionaries packages as well. Unless you feel it’s important to specify that this dictionary is specific for Persian as used in Iran compared to other regions where Persian is used, I’d like to use `fa` instead of `fa-IR`.

**Comment by wooorm** [comment]
@AhmadJavadiNejad Ping!

**Comment by AhmadJavadiNejad** [comment]
Yes I manually created this dictionary using a crawler. It is true that the dictionary is created manually using a crawler, but the source of the words is the official Iranian dictionary books.
Books like:
Dehkhoda Dictionary
Moin Encyclopedic Dictionary
You can check the resources specified in Google or Iranian libraries for more confidence.

If I want to explain it better. Alphabetically, we may be the same as other Persian-speaking countries. But in terms of the structure of words we are different.

**Comment by wooorm** [comment]
> It is true that the dictionary is created manually using a crawler, but the source of the words is the official Iranian dictionary books.

All right! That’s great to hear. But this project (`wooorm/dictionaries`) does not include original work: it packages dictionaries for easy usage in UTF-8 / JavaScript / Node. We get our dictionaries form other places.
Housing the code here would become unwieldy, as dictionaries typically require a lot of scripts and are sometimes actively maintained. That’s why I’d like to crawl from somewhere like lilak.

If you’d like to include your dictionary, it should a) be its own repo, similar to lilak, and b) have a proper affix file (spell checking is more complex than listing valid words, and affix files provide that).

> If I want to explain it better. Alphabetically, we may be the same as other Persian countries. But in terms of the structure of words we are different.

I don’t know if this is a response to either using lilak (1) or using the BCP-47 tag `fa` (2), so I’ll respond to both:

1. In the [readme of lilak](https://github.com/b00f/lilak), it states that a) the dictionary is dedicated to an Iranian author, and from the contributors that specified their location, it seems it’s all developed by Iranians.
Of course, I don’t understand Persian, but it seems to be that lilak is already doing what you are trying to do.
2. I understand there are differences in the language. But I thought Persian as written/spoken in Iran was the most used type of Persian? (WikiPedia states about 70m in Iran, 12m in Afghanistan [but Dari has its own `prs` code]). So first off, there are more specific codes to use for other varieties of Persian, and even if not, it’s similar to other languages, for example German, which has notably varieties German as used in Germany, German as spoken in Austria, and German as spoken is Switzerland. In this case, we use respectively `de`, `de-AT`, and `de-CH`. This is why I believe `fa` is fine for Persian as used in Iran.

**Pull request merged**
