### PR TITLE
Update Ukrainian (dict_uk#6.1.5)

### PR DESCRIPTION
**Pull request by sirenkovladd**
used last version dict_uk + used all dictionary
```sh
../../gradlew hunspellFull
```

### CODE REVIEW

**Comment by wooorm** [comment]
Sorry, I’m a bit swamped currently with other OSS work.

I’ll get to it in a couple months.

There are scripts in this repo to update things automatically, which I’ll use :)

**Comment by sirenkovladd** [comment]
Sorry, maybe you just merge it now before you update automatically in future?

**Comment by wooorm** [comment]
Hey, thanks for your patience!
Hmm, what good would that do? Merging this doesn’t release it?

**Comment by sirenkovladd** [comment]
I use https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-ukrainian
this extension uses this package

**Comment by wooorm** [comment]
Does it pull from Git instead of npm?

**Comment by sirenkovladd** [comment]
npm https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/uk_UA/package.json#L46C14-L46C14

**Comment by wooorm** [comment]
Terribly sorry, I really don‘t have time to investigate this repo and cut a release here the coming weeks. Could you ping me again in a month? Sorry, thanks!

**Pull request closed without merging**
