### PR TITLE
Add: Occitan Hunspell dictionary

### PR DESCRIPTION
**Pull request by Mejans**
PR in order to add the Occitan Hunspell dictionary.

### CODE REVIEW

**Comment by wooorm** [comment]
Heya! I’m open to adding Occitan, but: the dictionaries are crawled and generated from other sources: see the Contributing section at the bottom of the readme: https://github.com/wooorm/dictionaries#contributing.

**Comment by Mejans** [comment]
Ok ok, sources can be fetched here: https://gitlab.com/taissou/hunspell-files-for-occitan-lengadocian/-/tree/master/Files

**Comment by wooorm** [comment]
Fancy!

Could you update the PR to do that?

**Comment by Mejans** [comment]
Sure, tonight I'll give it a try!

**Comment by wooorm** [comment]
thanks!

The `crawl` function in bash is only one part of that file. Another important part is [`generate`](https://github.com/wooorm/dictionaries/blob/5fbbffcfa55acdcdeed53787edcbf4e5b69a86fd/script/crawl.sh#L529).
`generate` in bash takes the archive you crawled and makes the files you previously manually added.
Then, the final step is [`node script/generate`](https://github.com/wooorm/dictionaries/blob/5fbbffcfa55acdcdeed53787edcbf4e5b69a86fd/package.json#L45), which makes the node module out of it.

Finally: Is there a reason you tagged this dictionary as being specific to Occitan as spoken in France? Is this dictionary not applicable to Occitan as spoken in Spain/Italy/Monaco/etc?

**Comment by Mejans** [comment]
Yes Occitan is divided into dialects: Lengadocian (that of this PR), Gascon, Provençal, etc
There are words that don't exist or spelling differences. Dividing according to country is not useful.
English: oven, flour, April, fair
Lengadocian: forn, farina, abril, fièra
Gascon: horn, harina, abriu, hièra (initial F=>H, final L => U)
Provençal : horn, farina, abriu, fiera (final L => U)

**Comment by wooorm** [comment]
It seems Wikipedia states that due to Lengadocian’s central location, it’s somewhat seen as standard Occitan, that leads me to reason that `oc` can imply Lengadocian, and that the other variants of the language can use more specific tags.

Otherwise, `oc-lengadoc` might be more apt? ([ref](https://www.iana.org/assignments/lang-subtags-templates/lengadoc.txt))

https://www.iana.org/assignments/lang-subtags-templates/lengadoc.txt

**Comment by Mejans** [comment]
Yes, I see things like you do, oc implying lengadocian if there are no other indication.
At the moment, I haven't seen the sub tag being used, maybe SPIP for it included 7 versions for the Occitan.
You gather information quite fast for someone who didn't know about this language a few days ago ^^

**Comment by wooorm** [comment]
I see that the GitLab this is now crawled from takes the files from Dicollecte (http://www.dicollecte.org/dictionary.php?prj=oc), which redirects to Grammalecte, which is where we also get the French dictionary from. However, there, the [download links are broken](https://grammalecte.net/download.php?prj=oc). As I don’t speak Occitan (or French), could you indicate whether Grammalecte is indeed the canonical source? And do you know if there is a different download page perhaps? (for French there’s [this](https://grammalecte.net/#download) one, but that doesn’t seem available for Occitan).

Oh: and if `oc` is better than `oc-lengadoc` and `oc-fr`, could you rename the `oc-fr` -> `oc` folder here?

**Comment by Mejans** [comment]
Hello,
true, the goal is to eventually have one place to centralize the files and Dicollecte would be a really good place.
We are discussing the broken links and stuff.
In the meantime I rename the folder ;)
Would you agree to accept the PR?

**Comment by wooorm** [comment]
Thanks, released!
Would love it if you could communicate back where the the files are when they’re maintained on Dicollecte.

**Comment by Mejans** [comment]
Yes sure, I will come back to you when I have news

**Pull request merged**
